### ISSUE TITLE
Stardust demo for OpenGL comparison 

### ISSUE THREAD

**Issue by Nikolsi** [GameTechDev/stardust_vulkan#4]
Hello,
I conduct a research about the performance growth between Vulkan Api and OpenGL. I have seen a [https://www.youtube.com/watch?v=llOHf4eeSzc]( YouTube video from Intel), same demo Stardust for OpenGL. How can I get that? I want to compare OpenGL and Vulkan with my HD graphics.

Regards and thanks in advance

**Comment by ghost** [comment]
We don't have any immediate plans for adding OpenGL version to this repository. Currently it serves just as  sample application using Vulkan API. 

However we would gladly accept any contributions. 

I assume this answers the above issue, so I will close it for now.
